name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PATH_FOR_LINT: "src tests config"
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          source .bashrc
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-lint.txt

      - name: Run isort
        run: isort ${PATH_FOR_LINT} --check --profile black

      - name: Run black
        run: black ${PATH_FOR_LINT} --check

      - name: Run ruff
        run: ruff check ${PATH_FOR_LINT}

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          source .bashrc
          pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-test.txt
  
      - name: Run pytest
        run: pytest --cov=src tests
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ".bashrc,src,config,requirements,scripts,models,data"
          target: "/home/${{ env.SERVER_USER }}/otus-cicd"
      
      - name: Run install deps
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Setup
            cd /home/${{ env.SERVER_USER }}/otus-cicd
            source .bashrc
            ls -la

            # Install dependencies
            if [[ -d ".venv" ]]; then
              echo "Virtual environment already exists. Skipping creation."
            else
              python3 -m venv .venv
            fi

            # Activate the virtual environment and install dependencies
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Setup
            cd /home/${{ env.SERVER_USER }}/otus-cicd
            source .bashrc
            source .venv/bin/activate

            # Run the deploy script
            chmod +x scripts/entrypoint.sh
            bash scripts/entrypoint.sh
